//
// This code was generated by unite tool.
//
// Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
//
// 2019-04-26 19:16:43

// Generated from: game.go
package main

import (
	"github.com/muguangyi/unite/unite"
)

type igameproxy struct {
	u unite.IUnit
}

func (p *igameproxy) Start(level string) {
	err := p.u.Call("IGame", "Start", level)

	if nil != err {
		return
	}

}

var igameproxysucc bool = unite.Register("IGame", func(u unite.IUnit) interface{} { return &igameproxy{u: u} })
