//
// This code was generated by unite tool.
//
// Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
//
// 2019-04-26 19:16:43

// Generated from: lobby.go
package main

import (
	"github.com/muguangyi/unite/unite"
)

type ilobbyproxy struct {
	u unite.IUnit
}

var ilobbyproxysucc bool = unite.Register("ILobby", func(u unite.IUnit) interface{} { return &ilobbyproxy{u: u} })
