//
// This code was generated by unite tool.
//
// Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
//
// 2019-04-26 19:16:43

// Generated from: math.go
package main

import (
	"github.com/muguangyi/unite/unite"
)

type imathproxy struct {
	u unite.IUnit
}

func (p *imathproxy) Add(x float64, y float64) float64 {
	results, err := p.u.CallWithResult("IMath", "Add", x, y)

	if nil != err {
		return 0
	}

	return results[0].(float64)
}

var imathproxysucc bool = unite.Register("IMath", func(u unite.IUnit) interface{} { return &imathproxy{u: u} })
