//
// This code was generated by seek tool.
//
// Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
//
// 2019-04-29 16:51:55
//

package main

import (
	"github.com/muguangyi/seek"
)

// IGame from: game.go
type igameproxy struct {
	signaler seek.ISignaler
}

func (p *igameproxy) Start(level string) {
	err := p.signaler.Call("IGame", "Start", level)

	if nil != err {
		return
	}
}

// end IGame

// ILobby from: lobby.go
type ilobbyproxy struct {
	signaler seek.ISignaler
}

// end ILobby

// IMath from: math.go
type imathproxy struct {
	signaler seek.ISignaler
}

func (p *imathproxy) Add(x float64, y float64) float64 {
	results, err := p.signaler.CallWithResult("IMath", "Add", x, y)

	if nil != err {
		return 0
	}

	return results[0].(float64)
}

func (p *imathproxy) Print(msg string) {
	err := p.signaler.Call("IMath", "Print", msg)

	if nil != err {
		return
	}
}

// end IMath

// ILogin from: sub\login.go
type iloginproxy struct {
	signaler seek.ISignaler
}

func (p *iloginproxy) Login(name string, pwd string) bool {
	results, err := p.signaler.CallWithResult("ILogin", "Login", name, pwd)

	if nil != err {
		return false
	}

	return results[0].(bool)
}

func (p *iloginproxy) Logout() {
	err := p.signaler.Call("ILogin", "Logout")

	if nil != err {
		return
	}
}

// end ILogin

// Register to seek
var (
	igameproxysucc  bool = seek.Register("IGame", func(signaler seek.ISignaler) interface{} { return &igameproxy{signaler: signaler} })
	ilobbyproxysucc bool = seek.Register("ILobby", func(signaler seek.ISignaler) interface{} { return &ilobbyproxy{signaler: signaler} })
	imathproxysucc  bool = seek.Register("IMath", func(signaler seek.ISignaler) interface{} { return &imathproxy{signaler: signaler} })
	iloginproxysucc bool = seek.Register("ILogin", func(signaler seek.ISignaler) interface{} { return &iloginproxy{signaler: signaler} })
)
