language: go

go:
  - 1.12.x

env:
  - GO111MODULE=on

script:
  - go build
  - go test -race -coverprofile=coverage.txt -covermode=atomic

after_success:
  - bash <(curl -s https://codecov.io/bash) -t 5814ee15-8285-4e64-b1ef-3154b255fba0

