language: go
sudo: false
go:
  - 1.12.x

env:
  - GO111MODULE=on
  
before_script:
 - chmod +x scripts/codecov.sh

script:
  - ./scripts/codecov.sh
  - make build

after_success:
  - bash <(curl -s https://codecov.io/bash)

